# workflow file from npm docs but using bun
name: release
on:
  push:
    branches:
      - master # or main

permissions:
  contents: read # for checkout

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for trusted publishing and npm provenance
      attestations: write # to generate build provenance attestations
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v2 # v2
        with:
          bun-version: "latest"
      - name: Install dependencies
        run: bun install
      - name: Testing
        run: bun run build
      # - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
      #   run: npm audit signatures
      - name: Pack
        id: pack
        run: |
          bun pm pack
          PACKED_FILE=$(ls *.tgz | head -n1)
          echo "pkgfile=$PACKED_FILE" >> "$GITHUB_OUTPUT"
      - name: Generate Build Provenance
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: ${{ steps.pack.outputs.pkgfile }}

      - name: Publish to NPM Registry
        run: bunx npm publish "./${{ steps.pack.outputs.pkgfile }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
